<?php

namespace App\Presenters;


use Nette,
    Nette\Application\UI\Form;
use App\Model\CaseModel;
use App\Model\ExecutionModel;


class ExecutionPresenter extends BasePresenter
{

    /** @var UserModel */
    private $caseModel;

    /** @var ExecutionModel */
    private $executionModel;

    private $data = null;
    private  $case_id;

    /** @var Nette\Http\Session */
    private $session;

    /** @var Nette\Http\SessionSection */
    private $sessionSection;

    private $start_time;


    public function __construct(CaseModel $caseModel, ExecutionModel $executionModel, Nette\Http\Session $session)
    {

        $this->caseModel = $caseModel;
        $this->executionModel = $executionModel;
    }

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub

        $session = $this->getSession();
        $sessionSection = $session->getSection('sekcePromenna');
        $sessionSection->promenna = new \Nette\Utils\DateTime();
    }


    public function renderRun($case_id)
    {

        $this->case_id =$case_id;
        $this->template->case= $this->caseModel->getCase($case_id);
        $this->template->steps= $this->caseModel->getAllSteps($case_id);
    }



    protected function createComponentRunExecutionForm()
    {

        $form = new Form;


        $form->addHidden('start_time')->setDefaultValue($this->getSession('sekcePromenna')->promenna);
        $form->addHidden('spend_time')->setHtmlAttribute("id",'spend_time');
        $form->addHidden('run_by')->setDefaultValue($this->getUser()->getIdentity()->id);
        $form->addHidden('case_id')->setDefaultValue($this->case_id);
        $form->addHidden('status')->setDefaultValue('1');
        $form->addSubmit('run', 'Dokončit test')->setHtmlAttribute("id",'pass')->getControlPrototype()->setClass('btn btn-primary btn-lg btn-block');
        $form->onSuccess[] = [$this, 'RunExecution'];

        return $form;
    }

    public function RunExecution(Form $form, $values)
    {
        $id = $values["case_id"];
        $this->executionModel->addExecution($values);
        $this->flashMessage('Test byl dokončen jako úspěšný');
        $this->redirect("Case:detail",$id);



    }
}